FROM python:2.7.13
COPY . /6325830
RUN ["pip","install","six"]
RUN ["pip","install","pytest"]
RUN ["pip","install","py"]
RUN ["pip","install","sklearn"]
RUN ["pip","install","numpy"]
RUN ["pip","install","matplotlib"]
RUN ["pip","install","scikit-learn"]
CMD ["python","/6325830"]

