FROM python:2.7.13

LABEL maintainer="otc@gmail.com"

# install packages
RUN apt-get update
RUN pip install -U pip
RUN apt-get install -y software-properties-common
RUN pip install pymongo
RUN pip install datetime
RUN pip install bson

ADD snippet.py snippet.py
CMD python snippet.py
